# the location where the system dependent experiment config files are
"experiment_system_dependent_dir": '~/WORK/BerryPicker/cfg/experiment-config'
# the location where the experiment data is put
# the experiments's specific data will be _/className/runName
"experiment_data": '~/WORK/BerryPicker/data'
# the place where the external experiment/run stuff goes. Other ones can be used, but it is convenient to keep one referred from here
"experiment_external": '~/WORK/BerryPicker/data_external'

# the directory where the flows go on this machine (as well as other results...)
"flows_path": '~/WORK/BerryPicker-Flows'
# the directory where the demopacks go on this machine
"demopacks_path": '~/WORK/BerryPicker-Demopacks'


conv_vae:
  # Directory for the checkout of the CONV_VAE project 
  # https://github.com/julian-8897/Conv-VAE-PyTorch
  code_dir: '~/WORK/BerryPicker/src/Conv-VAE-PyTorch'
